//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MingMongoPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MingMongoPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arbiter {
            get {
                object obj = ResourceManager.GetObject("arbiter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap collection {
            get {
                object obj = ResourceManager.GetObject("collection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap collection_add {
            get {
                object obj = ResourceManager.GetObject("collection_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap collection_copy {
            get {
                object obj = ResourceManager.GetObject("collection_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap collection_delete {
            get {
                object obj = ResourceManager.GetObject("collection_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap collections {
            get {
                object obj = ResourceManager.GetObject("collections", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap collections_compact {
            get {
                object obj = ResourceManager.GetObject("collections_compact", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to filtered properties.
        /// </summary>
        public static string CollectionView_AddFilter {
            get {
                return ResourceManager.GetString("CollectionView_AddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to sorted properties.
        /// </summary>
        public static string CollectionView_AddSort {
            get {
                return ResourceManager.GetString("CollectionView_AddSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string CollectionView_Asc {
            get {
                return ResourceManager.GetString("CollectionView_Asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string CollectionView_Desc {
            get {
                return ResourceManager.GetString("CollectionView_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection View {0}:{1}/{2}.{3}.
        /// </summary>
        public static string CollectionView_Description {
            get {
                return ResourceManager.GetString("CollectionView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents:.
        /// </summary>
        public static string CollectionView_Documents {
            get {
                return ResourceManager.GetString("CollectionView_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by.
        /// </summary>
        public static string CollectionView_Filter {
            get {
                return ResourceManager.GetString("CollectionView_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View flattened.
        /// </summary>
        public static string CollectionView_Flat {
            get {
                return ResourceManager.GetString("CollectionView_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string CollectionView_Header_Property {
            get {
                return ResourceManager.GetString("CollectionView_Header_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string CollectionView_Header_Type {
            get {
                return ResourceManager.GetString("CollectionView_Header_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string CollectionView_Header_Value {
            get {
                return ResourceManager.GetString("CollectionView_Header_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide filter panel.
        /// </summary>
        public static string CollectionView_HideFilter {
            get {
                return ResourceManager.GetString("CollectionView_HideFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide sorting panel.
        /// </summary>
        public static string CollectionView_HideSort {
            get {
                return ResourceManager.GetString("CollectionView_HideSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View as hierarchy.
        /// </summary>
        public static string CollectionView_Hierarchy {
            get {
                return ResourceManager.GetString("CollectionView_Hierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string CollectionView_Loading {
            get {
                return ResourceManager.GetString("CollectionView_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        public static string CollectionView_Next {
            get {
                return ResourceManager.GetString("CollectionView_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string CollectionView_Of {
            get {
                return ResourceManager.GetString("CollectionView_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string CollectionView_Page {
            get {
                return ResourceManager.GetString("CollectionView_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items per page.
        /// </summary>
        public static string CollectionView_PageSize {
            get {
                return ResourceManager.GetString("CollectionView_PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        public static string CollectionView_Previous {
            get {
                return ResourceManager.GetString("CollectionView_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string CollectionView_Refresh {
            get {
                return ResourceManager.GetString("CollectionView_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show filter panel.
        /// </summary>
        public static string CollectionView_ShowFilter {
            get {
                return ResourceManager.GetString("CollectionView_ShowFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show sorting panel.
        /// </summary>
        public static string CollectionView_ShowSort {
            get {
                return ResourceManager.GetString("CollectionView_ShowSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string CollectionView_Sort {
            get {
                return ResourceManager.GetString("CollectionView_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string CollectionView_Title {
            get {
                return ResourceManager.GetString("CollectionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap columns {
            get {
                object obj = ResourceManager.GetObject("columns", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: This command obtains a write lock on the affected database and will block other operations until it has completed.\n\n\nAre you sure you want to compact all the collections in the database {0}?.
        /// </summary>
        public static string CompactCollections_Confirm {
            get {
                return ResourceManager.GetString("CompactCollections_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: This command obtains a write lock on the affected database and will block other operations until it has completed.\n\n\nAre you sure you want to compact all the collections in the server {0}:{1}?.
        /// </summary>
        public static string CompactCollections_ConfirmAll {
            get {
                return ResourceManager.GetString("CompactCollections_ConfirmAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compacting collection {0}.{1}.
        /// </summary>
        public static string CompactCollections_DescCompacting {
            get {
                return ResourceManager.GetString("CompactCollections_DescCompacting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string CompactCollections_DescComplete {
            get {
                return ResourceManager.GetString("CompactCollections_DescComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counting collections.
        /// </summary>
        public static string CompactCollections_DescCounting {
            get {
                return ResourceManager.GetString("CompactCollections_DescCounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred compacting the collection. {0}.
        /// </summary>
        public static string CompactCollections_Error {
            get {
                return ResourceManager.GetString("CompactCollections_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compacting Collections.
        /// </summary>
        public static string CompactCollections_Title {
            get {
                return ResourceManager.GetString("CompactCollections_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the collection &apos;{0}&apos;?.
        /// </summary>
        public static string Confirm_DeleteCollection {
            get {
                return ResourceManager.GetString("Confirm_DeleteCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the database &apos;{0}&apos;?.
        /// </summary>
        public static string Confirm_DeleteDatabase {
            get {
                return ResourceManager.GetString("Confirm_DeleteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap console {
            get {
                object obj = ResourceManager.GetObject("console", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Alt + Enter to execute.
        /// </summary>
        public static string Console_AltEnterTip {
            get {
                return ResourceManager.GetString("Console_AltEnterTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;clear&apos; to clear the output window.
        /// </summary>
        public static string Console_ClearTip {
            get {
                return ResourceManager.GetString("Console_ClearTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console {0}:{1}.
        /// </summary>
        public static string Console_Description {
            get {
                return ResourceManager.GetString("Console_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening mongo.exe, the stored path to mongo.exe will be cleared.
        /// </summary>
        public static string Console_ErrorOpening {
            get {
                return ResourceManager.GetString("Console_ErrorOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please locate the file mongo.exe\n\n\nYou will only have to do this once, the path will be stored for future use.
        /// </summary>
        public static string Console_LocateDesc {
            get {
                return ResourceManager.GetString("Console_LocateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mongo.exe path required.
        /// </summary>
        public static string Console_LocateTitle {
            get {
                return ResourceManager.GetString("Console_LocateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}.
        /// </summary>
        public static string Console_Title {
            get {
                return ResourceManager.GetString("Console_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This does not appear to a path to mongo.exe\n\n\nYou will be prompted to locate the file again next time you open the console.
        /// </summary>
        public static string Console_WrongFileDesc {
            get {
                return ResourceManager.GetString("Console_WrongFileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mongo.exe path error.
        /// </summary>
        public static string Console_WrongFileTitle {
            get {
                return ResourceManager.GetString("Console_WrongFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied {0} documents.
        /// </summary>
        public static string CopyCollection_Copying {
            get {
                return ResourceManager.GetString("CopyCollection_Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting document count.
        /// </summary>
        public static string CopyCollection_Counting {
            get {
                return ResourceManager.GetString("CopyCollection_Counting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection {0} already exists.
        /// </summary>
        public static string CopyCollection_Exists {
            get {
                return ResourceManager.GetString("CopyCollection_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying Collection.
        /// </summary>
        public static string CopyCollection_OpTitle {
            get {
                return ResourceManager.GetString("CopyCollection_OpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for the new collection.
        /// </summary>
        public static string CopyCollection_Prompt {
            get {
                return ResourceManager.GetString("CopyCollection_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Collection.
        /// </summary>
        public static string CopyCollection_Title {
            get {
                return ResourceManager.GetString("CopyCollection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CopyCollections_CancelButton {
            get {
                return ResourceManager.GetString("CopyCollections_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyCollections_CopyButton {
            get {
                return ResourceManager.GetString("CopyCollections_CopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred copying the collection. {0}.
        /// </summary>
        public static string CopyCollections_Error {
            get {
                return ResourceManager.GetString("CopyCollections_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string CopyCollections_ErrorMessageTitle {
            get {
                return ResourceManager.GetString("CopyCollections_ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following database or collection names are not valid:\n\n\n{0}\n\nPlease correct these before proceeding..
        /// </summary>
        public static string CopyCollections_InvalidNames {
            get {
                return ResourceManager.GetString("CopyCollections_InvalidNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading available collections....
        /// </summary>
        public static string CopyCollections_LoadingCollections {
            get {
                return ResourceManager.GetString("CopyCollections_LoadingCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading target databases....
        /// </summary>
        public static string CopyCollections_LoadingTargets {
            get {
                return ResourceManager.GetString("CopyCollections_LoadingTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Collection Name.
        /// </summary>
        public static string CopyCollections_NewCollection {
            get {
                return ResourceManager.GetString("CopyCollections_NewCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected any collections to copy.
        /// </summary>
        public static string CopyCollections_NoneSelected {
            get {
                return ResourceManager.GetString("CopyCollections_NoneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to Copy....
        /// </summary>
        public static string CopyCollections_PrepareTitle {
            get {
                return ResourceManager.GetString("CopyCollections_PrepareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string CopyCollections_Source {
            get {
                return ResourceManager.GetString("CopyCollections_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Collection.
        /// </summary>
        public static string CopyCollections_SourceCollection {
            get {
                return ResourceManager.GetString("CopyCollections_SourceCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string CopyCollections_Target {
            get {
                return ResourceManager.GetString("CopyCollections_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Database.
        /// </summary>
        public static string CopyCollections_TargetDatabase {
            get {
                return ResourceManager.GetString("CopyCollections_TargetDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure all target databases and collection names are set.
        /// </summary>
        public static string CopyCollections_TargetError {
            get {
                return ResourceManager.GetString("CopyCollections_TargetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following collections exist on the target server:\n\n\n{0}\n\nChange the new collection names or delete these collections before proceeding..
        /// </summary>
        public static string CopyCollections_TargetsExists {
            get {
                return ResourceManager.GetString("CopyCollections_TargetsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Collections.
        /// </summary>
        public static string CopyCollections_Title {
            get {
                return ResourceManager.GetString("CopyCollections_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied {0} collection(s): {1} document(s) in total.
        /// </summary>
        public static string CopyingCollections_Complete {
            get {
                return ResourceManager.GetString("CopyingCollections_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying collection {0}.{1} to {2}.{3}: {4} document(s) copied.
        /// </summary>
        public static string CopyingCollections_Copying {
            get {
                return ResourceManager.GetString("CopyingCollections_Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting document count.
        /// </summary>
        public static string CopyingCollections_Counting {
            get {
                return ResourceManager.GetString("CopyingCollections_Counting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating indexes on {0}.{1}.
        /// </summary>
        public static string CopyingCollections_CreatingIndexes {
            get {
                return ResourceManager.GetString("CopyingCollections_CreatingIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid collection name.
        /// </summary>
        public static string CopyingCollections_InvalidName {
            get {
                return ResourceManager.GetString("CopyingCollections_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1} is not the primary node.
        /// </summary>
        public static string CopyingCollections_NotMaster {
            get {
                return ResourceManager.GetString("CopyingCollections_NotMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0} collection(s)....
        /// </summary>
        public static string CopyingCollections_Title {
            get {
                return ResourceManager.GetString("CopyingCollections_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating collection {0}.
        /// </summary>
        public static string CreateCollection_OperationTitle {
            get {
                return ResourceManager.GetString("CreateCollection_OperationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name for the new collection.
        /// </summary>
        public static string CreateCollection_Prompt {
            get {
                return ResourceManager.GetString("CreateCollection_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Collection.
        /// </summary>
        public static string CreateCollection_Title {
            get {
                return ResourceManager.GetString("CreateCollection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database {0} already exists.
        /// </summary>
        public static string CreateDatabase_Exists {
            get {
                return ResourceManager.GetString("CreateDatabase_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid database name.
        /// </summary>
        public static string CreateDatabase_InvalidName {
            get {
                return ResourceManager.GetString("CreateDatabase_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating database {0}.
        /// </summary>
        public static string CreateDatabase_OperationTitle {
            get {
                return ResourceManager.GetString("CreateDatabase_OperationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name for the new database.
        /// </summary>
        public static string CreateDatabase_Prompt {
            get {
                return ResourceManager.GetString("CreateDatabase_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Database.
        /// </summary>
        public static string CreateDatabase_Title {
            get {
                return ResourceManager.GetString("CreateDatabase_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap database {
            get {
                object obj = ResourceManager.GetObject("database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap database_add {
            get {
                object obj = ResourceManager.GetObject("database_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap database_collection {
            get {
                object obj = ResourceManager.GetObject("database_collection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap database_copy {
            get {
                object obj = ResourceManager.GetObject("database_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap database_delete {
            get {
                object obj = ResourceManager.GetObject("database_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DeleteColsDBs_CancelButton {
            get {
                return ResourceManager.GetString("DeleteColsDBs_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteColsDBs_DeleteButton {
            get {
                return ResourceManager.GetString("DeleteColsDBs_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Databases/Collections.
        /// </summary>
        public static string DeleteColsDBs_Title {
            get {
                return ResourceManager.GetString("DeleteColsDBs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting document....
        /// </summary>
        public static string DeleteDocument_Deleting {
            get {
                return ResourceManager.GetString("DeleteDocument_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap document {
            get {
                object obj = ResourceManager.GetObject("document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap document_add {
            get {
                object obj = ResourceManager.GetObject("document_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap document_delete {
            get {
                object obj = ResourceManager.GetObject("document_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap documents {
            get {
                object obj = ResourceManager.GetObject("documents", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate JavaScript {0}:{1}/{2}.
        /// </summary>
        public static string EvaluateJS_Description {
            get {
                return ResourceManager.GetString("EvaluateJS_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute [Alt + Enter].
        /// </summary>
        public static string EvaluateJS_Evaluate {
            get {
                return ResourceManager.GetString("EvaluateJS_Evaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluating....
        /// </summary>
        public static string EvaluateJS_Evaluating {
            get {
                return ResourceManager.GetString("EvaluateJS_Evaluating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string EvaluateJS_Title {
            get {
                return ResourceManager.GetString("EvaluateJS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap filter {
            get {
                object obj = ResourceManager.GetObject("filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap index {
            get {
                object obj = ResourceManager.GetObject("index", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparse.
        /// </summary>
        public static string IndexControl_Sparse {
            get {
                return ResourceManager.GetString("IndexControl_Sparse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique.
        /// </summary>
        public static string IndexControl_Unique {
            get {
                return ResourceManager.GetString("IndexControl_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap indexes {
            get {
                object obj = ResourceManager.GetObject("indexes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string IndexType_Ascending {
            get {
                return ResourceManager.GetString("IndexType_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ASC].
        /// </summary>
        public static string IndexType_AscendingAbbr {
            get {
                return ResourceManager.GetString("IndexType_AscendingAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string IndexType_Descending {
            get {
                return ResourceManager.GetString("IndexType_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DSC].
        /// </summary>
        public static string IndexType_DescendingAbbr {
            get {
                return ResourceManager.GetString("IndexType_DescendingAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geospatial.
        /// </summary>
        public static string IndexType_Geospatial {
            get {
                return ResourceManager.GetString("IndexType_Geospatial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GEO].
        /// </summary>
        public static string IndexType_GeospatialAbbr {
            get {
                return ResourceManager.GetString("IndexType_GeospatialAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap log {
            get {
                object obj = ResourceManager.GetObject("log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Watch {0}:{1}.
        /// </summary>
        public static string LogWatch_Description {
            get {
                return ResourceManager.GetString("LogWatch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (highest).
        /// </summary>
        public static string LogWatch_High {
            get {
                return ResourceManager.GetString("LogWatch_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log to view.
        /// </summary>
        public static string LogWatch_Log {
            get {
                return ResourceManager.GetString("LogWatch_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (lowest).
        /// </summary>
        public static string LogWatch_Low {
            get {
                return ResourceManager.GetString("LogWatch_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string LogWatch_Pause {
            get {
                return ResourceManager.GetString("LogWatch_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string LogWatch_Resume {
            get {
                return ResourceManager.GetString("LogWatch_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}.
        /// </summary>
        public static string LogWatch_Title {
            get {
                return ResourceManager.GetString("LogWatch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbosity.
        /// </summary>
        public static string LogWatch_Verbosity {
            get {
                return ResourceManager.GetString("LogWatch_Verbosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying indexes.
        /// </summary>
        public static string ManageIndexes_Applying {
            get {
                return ResourceManager.GetString("ManageIndexes_Applying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string ManageIndexes_Ascending {
            get {
                return ResourceManager.GetString("ManageIndexes_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ManageIndexes_CancelButton {
            get {
                return ResourceManager.GetString("ManageIndexes_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Property.
        /// </summary>
        public static string ManageIndexes_Column0Title {
            get {
                return ResourceManager.GetString("ManageIndexes_Column0Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Type.
        /// </summary>
        public static string ManageIndexes_Column1Title {
            get {
                return ResourceManager.GetString("ManageIndexes_Column1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating index {0}.
        /// </summary>
        public static string ManageIndexes_Creating {
            get {
                return ResourceManager.GetString("ManageIndexes_Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string ManageIndexes_Descending {
            get {
                return ResourceManager.GetString("ManageIndexes_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropping exising indexes.
        /// </summary>
        public static string ManageIndexes_Dropping {
            get {
                return ResourceManager.GetString("ManageIndexes_Dropping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} index(es) were not created.{1}.
        /// </summary>
        public static string ManageIndexes_Fail {
            get {
                return ResourceManager.GetString("ManageIndexes_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geospatial.
        /// </summary>
        public static string ManageIndexes_Geospatial {
            get {
                return ResourceManager.GetString("ManageIndexes_Geospatial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index {0} has a geospatial index which was not the first property in the index.
        /// </summary>
        public static string ManageIndexes_GeospatialNotFirst {
            get {
                return ResourceManager.GetString("ManageIndexes_GeospatialNotFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index {0} contains a property not valid for a geospatial index.
        /// </summary>
        public static string ManageIndexes_InvalidGeospatial {
            get {
                return ResourceManager.GetString("ManageIndexes_InvalidGeospatial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index {0} contains a property with duplicate entries, a unique index could not be created.
        /// </summary>
        public static string ManageIndexes_InvalidUnique {
            get {
                return ResourceManager.GetString("ManageIndexes_InvalidUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ManageIndexes_SaveButton {
            get {
                return ResourceManager.GetString("ManageIndexes_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} index(es) created.
        /// </summary>
        public static string ManageIndexes_Success {
            get {
                return ResourceManager.GetString("ManageIndexes_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Indexes - {0}.
        /// </summary>
        public static string ManageIndexes_Title {
            get {
                return ResourceManager.GetString("ManageIndexes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred creating index {0}. {1}.
        /// </summary>
        public static string ManageIndexes_UnknownError {
            get {
                return ResourceManager.GetString("ManageIndexes_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Mongo.
        /// </summary>
        public static string Menu_Data {
            get {
                return ResourceManager.GetString("Menu_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add _Collection....
        /// </summary>
        public static string MenuItem_AddCollection {
            get {
                return ResourceManager.GetString("MenuItem_AddCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add _Database....
        /// </summary>
        public static string MenuItem_AddDatabase {
            get {
                return ResourceManager.GetString("MenuItem_AddDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact All Collections....
        /// </summary>
        public static string MenuItem_CompactCollections {
            get {
                return ResourceManager.GetString("MenuItem_CompactCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Collection....
        /// </summary>
        public static string MenuItem_CopyCollection {
            get {
                return ResourceManager.GetString("MenuItem_CopyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Collections....
        /// </summary>
        public static string MenuItem_CopyCollections {
            get {
                return ResourceManager.GetString("MenuItem_CopyCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Database....
        /// </summary>
        public static string MenuItem_CopyDatabase {
            get {
                return ResourceManager.GetString("MenuItem_CopyDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Document.
        /// </summary>
        public static string MenuItem_CopyDocument {
            get {
                return ResourceManager.GetString("MenuItem_CopyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Collection....
        /// </summary>
        public static string MenuItem_DeleteCollection {
            get {
                return ResourceManager.GetString("MenuItem_DeleteCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete databases/collections....
        /// </summary>
        public static string MenuItem_DeleteColllectionsDBs {
            get {
                return ResourceManager.GetString("MenuItem_DeleteColllectionsDBs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Database....
        /// </summary>
        public static string MenuItem_DeleteDatabase {
            get {
                return ResourceManager.GetString("MenuItem_DeleteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Document.
        /// </summary>
        public static string MenuItem_DeleteDocument {
            get {
                return ResourceManager.GetString("MenuItem_DeleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate JavaScript.
        /// </summary>
        public static string MenuItem_EvalJS {
            get {
                return ResourceManager.GetString("MenuItem_EvalJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Indexes....
        /// </summary>
        public static string MenuItem_ManageIndexes {
            get {
                return ResourceManager.GetString("MenuItem_ManageIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Console.
        /// </summary>
        public static string MenuItem_OpenConsole {
            get {
                return ResourceManager.GetString("MenuItem_OpenConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Collection....
        /// </summary>
        public static string MenuItem_RenameCollection {
            get {
                return ResourceManager.GetString("MenuItem_RenameCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Database....
        /// </summary>
        public static string MenuItem_RenameDatabase {
            get {
                return ResourceManager.GetString("MenuItem_RenameDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Status.
        /// </summary>
        public static string MenuItem_SystemStatus {
            get {
                return ResourceManager.GetString("MenuItem_SystemStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View Collection.
        /// </summary>
        public static string MenuItem_ViewData {
            get {
                return ResourceManager.GetString("MenuItem_ViewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Logs.
        /// </summary>
        public static string MenuItem_WatchLogs {
            get {
                return ResourceManager.GetString("MenuItem_WatchLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mongo_treeview {
            get {
                object obj = ResourceManager.GetObject("mongo_treeview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MongoDB Plugin.
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MongoDB.
        /// </summary>
        public static string PluginTitle {
            get {
                return ResourceManager.GetString("PluginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap previous {
            get {
                object obj = ResourceManager.GetObject("previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap primary {
            get {
                object obj = ResourceManager.GetObject("primary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new name for the collection.
        /// </summary>
        public static string RenameCollection_Prompt {
            get {
                return ResourceManager.GetString("RenameCollection_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Collection.
        /// </summary>
        public static string RenameCollection_Title {
            get {
                return ResourceManager.GetString("RenameCollection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection {0} already exists.
        /// </summary>
        public static string Renaming_CollectionExists {
            get {
                return ResourceManager.GetString("Renaming_CollectionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming {0} to {1}.
        /// </summary>
        public static string Renaming_Description {
            get {
                return ResourceManager.GetString("Renaming_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred renaming the collection. {0}.
        /// </summary>
        public static string Renaming_GenericError {
            get {
                return ResourceManager.GetString("Renaming_GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid collection name.
        /// </summary>
        public static string Renaming_InvalidName {
            get {
                return ResourceManager.GetString("Renaming_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1} is not the primary node.
        /// </summary>
        public static string Renaming_NotMaster {
            get {
                return ResourceManager.GetString("Renaming_NotMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming {0}.
        /// </summary>
        public static string Renaming_Title {
            get {
                return ResourceManager.GetString("Renaming_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap script {
            get {
                object obj = ResourceManager.GetObject("script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap secondary {
            get {
                object obj = ResourceManager.GetObject("secondary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap server_status {
            get {
                object obj = ResourceManager.GetObject("server_status", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        public static string ServerStatus_Global {
            get {
                return ResourceManager.GetString("ServerStatus_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} Lock Time.
        /// </summary>
        public static string ServerStatus_LockDesc {
            get {
                return ResourceManager.GetString("ServerStatus_LockDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string ServerStatus_Read {
            get {
                return ResourceManager.GetString("ServerStatus_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        public static string ServerStatus_Write {
            get {
                return ResourceManager.GetString("ServerStatus_Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting....
        /// </summary>
        public static string Status_Deleting {
            get {
                return ResourceManager.GetString("Status_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string SystemOverview_Connections {
            get {
                return ResourceManager.GetString("SystemOverview_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string SystemOverview_Interval {
            get {
                return ResourceManager.GetString("SystemOverview_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.5 seconds.
        /// </summary>
        public static string SystemOverview_Interval0 {
            get {
                return ResourceManager.GetString("SystemOverview_Interval0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 second.
        /// </summary>
        public static string SystemOverview_Interval1 {
            get {
                return ResourceManager.GetString("SystemOverview_Interval1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 seconds.
        /// </summary>
        public static string SystemOverview_Interval2 {
            get {
                return ResourceManager.GetString("SystemOverview_Interval2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 seconds.
        /// </summary>
        public static string SystemOverview_Interval3 {
            get {
                return ResourceManager.GetString("SystemOverview_Interval3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute.
        /// </summary>
        public static string SystemOverview_Interval4 {
            get {
                return ResourceManager.GetString("SystemOverview_Interval4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Memory.
        /// </summary>
        public static string SystemOverview_MemoryTitle {
            get {
                return ResourceManager.GetString("SystemOverview_MemoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network In.
        /// </summary>
        public static string SystemOverview_NetworkIn {
            get {
                return ResourceManager.GetString("SystemOverview_NetworkIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Out.
        /// </summary>
        public static string SystemOverview_NetworkOut {
            get {
                return ResourceManager.GetString("SystemOverview_NetworkOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span.
        /// </summary>
        public static string SystemOverview_Span {
            get {
                return ResourceManager.GetString("SystemOverview_Span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute.
        /// </summary>
        public static string SystemOverview_Span0 {
            get {
                return ResourceManager.GetString("SystemOverview_Span0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 minutes.
        /// </summary>
        public static string SystemOverview_Span1 {
            get {
                return ResourceManager.GetString("SystemOverview_Span1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        public static string SystemOverview_Span2 {
            get {
                return ResourceManager.GetString("SystemOverview_Span2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string SystemOverview_Span3 {
            get {
                return ResourceManager.GetString("SystemOverview_Span3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string SystemOverview_TotalOps {
            get {
                return ResourceManager.GetString("SystemOverview_TotalOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Status {0}:{1}.
        /// </summary>
        public static string SystemStatus_Description {
            get {
                return ResourceManager.GetString("SystemStatus_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}.
        /// </summary>
        public static string SystemStatus_Title {
            get {
                return ResourceManager.GetString("SystemStatus_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tree {
            get {
                object obj = ResourceManager.GetObject("tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections.
        /// </summary>
        public static string TreeView_Collections {
            get {
                return ResourceManager.GetString("TreeView_Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Connect.
        /// </summary>
        public static string TreeView_ConnectionFailure {
            get {
                return ResourceManager.GetString("TreeView_ConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexes.
        /// </summary>
        public static string TreeView_Indexes {
            get {
                return ResourceManager.GetString("TreeView_Indexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Collections.
        /// </summary>
        public static string TreeView_NoCollections {
            get {
                return ResourceManager.GetString("TreeView_NoCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Databases.
        /// </summary>
        public static string TreeView_NoDatabases {
            get {
                return ResourceManager.GetString("TreeView_NoDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Indexes.
        /// </summary>
        public static string TreeView_NoIndexes {
            get {
                return ResourceManager.GetString("TreeView_NoIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string TreeView_Properties {
            get {
                return ResourceManager.GetString("TreeView_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap view {
            get {
                object obj = ResourceManager.GetObject("view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
