//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MingMongoPlugin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int CollectionViewPageSize {
            get {
                return ((int)(this["CollectionViewPageSize"]));
            }
            set {
                this["CollectionViewPageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CollectionViewShowSort {
            get {
                return ((bool)(this["CollectionViewShowSort"]));
            }
            set {
                this["CollectionViewShowSort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CollectionViewShowFilter {
            get {
                return ((bool)(this["CollectionViewShowFilter"]));
            }
            set {
                this["CollectionViewShowFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CopyCollectionsColumn1 {
            get {
                return ((int)(this["CopyCollectionsColumn1"]));
            }
            set {
                this["CopyCollectionsColumn1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CopyCollectionsColumn2 {
            get {
                return ((int)(this["CopyCollectionsColumn2"]));
            }
            set {
                this["CopyCollectionsColumn2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CopyCollectionsColumn3 {
            get {
                return ((int)(this["CopyCollectionsColumn3"]));
            }
            set {
                this["CopyCollectionsColumn3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CopyCollectionsWidth {
            get {
                return ((int)(this["CopyCollectionsWidth"]));
            }
            set {
                this["CopyCollectionsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CopyCollectionsHeight {
            get {
                return ((int)(this["CopyCollectionsHeight"]));
            }
            set {
                this["CopyCollectionsHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CopyCollectionsLeftPaneWidth {
            get {
                return ((int)(this["CopyCollectionsLeftPaneWidth"]));
            }
            set {
                this["CopyCollectionsLeftPaneWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ManageIndexesWidth {
            get {
                return ((int)(this["ManageIndexesWidth"]));
            }
            set {
                this["ManageIndexesWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ManageIndexesHeight {
            get {
                return ((int)(this["ManageIndexesHeight"]));
            }
            set {
                this["ManageIndexesHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConsoleForeground {
            get {
                return ((string)(this["ConsoleForeground"]));
            }
            set {
                this["ConsoleForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConsoleBackground {
            get {
                return ((string)(this["ConsoleBackground"]));
            }
            set {
                this["ConsoleBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MongoExeLocation {
            get {
                return ((string)(this["MongoExeLocation"]));
            }
            set {
                this["MongoExeLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SystemOverviewInterval {
            get {
                return ((int)(this["SystemOverviewInterval"]));
            }
            set {
                this["SystemOverviewInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SystemOverviewSpan {
            get {
                return ((int)(this["SystemOverviewSpan"]));
            }
            set {
                this["SystemOverviewSpan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DeleteCollectionsDBsWidth {
            get {
                return ((int)(this["DeleteCollectionsDBsWidth"]));
            }
            set {
                this["DeleteCollectionsDBsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DeleteCollectionsDBsHeight {
            get {
                return ((int)(this["DeleteCollectionsDBsHeight"]));
            }
            set {
                this["DeleteCollectionsDBsHeight"] = value;
            }
        }
    }
}
