//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ming.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ming.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        public static string About_Component {
            get {
                return ResourceManager.GetString("About_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright ©2012 Steve John.
        /// </summary>
        public static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string About_OK {
            get {
                return ResourceManager.GetString("About_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Hub.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://stevejohn.me.
        /// </summary>
        public static string About_WebsiteLink {
            get {
                return ResourceManager.GetString("About_WebsiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hub.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Connect_AddButton {
            get {
                return ResourceManager.GetString("Connect_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Connect_CancelButton {
            get {
                return ResourceManager.GetString("Connect_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the connection {0} for {1}?.
        /// </summary>
        public static string Connect_Confirm_Delete_Message {
            get {
                return ResourceManager.GetString("Connect_Confirm_Delete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection to {0} for {1} already exists.
        /// </summary>
        public static string Connect_Error_Duplicate {
            get {
                return ResourceManager.GetString("Connect_Error_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Adding Connection.
        /// </summary>
        public static string Connect_Error_Title {
            get {
                return ResourceManager.GetString("Connect_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Connect_Host {
            get {
                return ResourceManager.GetString("Connect_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Connect_Name {
            get {
                return ResourceManager.GetString("Connect_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Connect_Password {
            get {
                return ResourceManager.GetString("Connect_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Connect_Port {
            get {
                return ResourceManager.GetString("Connect_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing....
        /// </summary>
        public static string Connect_Progress_Testing {
            get {
                return ResourceManager.GetString("Connect_Progress_Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Connect_Service {
            get {
                return ResourceManager.GetString("Connect_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Connect_TestButton {
            get {
                return ResourceManager.GetString("Connect_TestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Service.
        /// </summary>
        public static string Connect_Title {
            get {
                return ResourceManager.GetString("Connect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Connect_Username {
            get {
                return ResourceManager.GetString("Connect_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string Connections_PanelTitle {
            get {
                return ResourceManager.GetString("Connections_PanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .json.
        /// </summary>
        public static string Export_DefaultExtension {
            get {
                return ResourceManager.GetString("Export_DefaultExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string Export_DefaultFileName {
            get {
                return ResourceManager.GetString("Export_DefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred writing the connections file.
        /// </summary>
        public static string Export_Error {
            get {
                return ResourceManager.GetString("Export_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json Files|*.json.
        /// </summary>
        public static string Export_Filter {
            get {
                return ResourceManager.GetString("Export_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Connections.
        /// </summary>
        public static string Export_SaveTitle {
            get {
                return ResourceManager.GetString("Export_SaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections Exported.
        /// </summary>
        public static string Export_Success {
            get {
                return ResourceManager.GetString("Export_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hub Controls.
        /// </summary>
        public static string Help_ControlsName {
            get {
                return ResourceManager.GetString("Help_ControlsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hub Plugin Interfaces.
        /// </summary>
        public static string Help_InterfacesName {
            get {
                return ResourceManager.GetString("Help_InterfacesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap import {
            get {
                object obj = ResourceManager.GetObject("import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred reading the connections file.
        /// </summary>
        public static string Import_Error {
            get {
                return ResourceManager.GetString("Import_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Connections.
        /// </summary>
        public static string Import_OpenTitle {
            get {
                return ResourceManager.GetString("Import_OpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections Imported.
        /// </summary>
        public static string Import_Success {
            get {
                return ResourceManager.GetString("Import_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Offline.
        /// </summary>
        public static string LicenceEntry_ActivateOffline {
            get {
                return ResourceManager.GetString("LicenceEntry_ActivateOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Online.
        /// </summary>
        public static string LicenceEntry_ActivateOnline {
            get {
                return ResourceManager.GetString("LicenceEntry_ActivateOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have purchased a licence, you can enter your email address below and activate online..
        /// </summary>
        public static string LicenceEntry_HowToActivate {
            get {
                return ResourceManager.GetString("LicenceEntry_HowToActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this machine does not have general internet access, enter your email address above and licence code below to activate..
        /// </summary>
        public static string LicenceEntry_NoInternet {
            get {
                return ResourceManager.GetString("LicenceEntry_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://outsidecontextproblem.com/purchase.
        /// </summary>
        public static string LicenceEntry_PurchaseLink {
            get {
                return ResourceManager.GetString("LicenceEntry_PurchaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outsidecontextproblem.com/purchase.
        /// </summary>
        public static string LicenceEntry_PurchaseLinkText {
            get {
                return ResourceManager.GetString("LicenceEntry_PurchaseLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can purchase a licence here:.
        /// </summary>
        public static string LicenceEntry_PurchaseText {
            get {
                return ResourceManager.GetString("LicenceEntry_PurchaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but your Hub trial period has expired..
        /// </summary>
        public static string LicenceEntry_SorryExpired {
            get {
                return ResourceManager.GetString("LicenceEntry_SorryExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Period Expired.
        /// </summary>
        public static string LicenceEntry_Title {
            get {
                return ResourceManager.GetString("LicenceEntry_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hub.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Connect....
        /// </summary>
        public static string Menu_File_Connect {
            get {
                return ResourceManager.GetString("Menu_File_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Disconnect.
        /// </summary>
        public static string Menu_File_Disconnect {
            get {
                return ResourceManager.GetString("Menu_File_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export Connections....
        /// </summary>
        public static string Menu_File_Export {
            get {
                return ResourceManager.GetString("Menu_File_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import Connections....
        /// </summary>
        public static string Menu_File_Import {
            get {
                return ResourceManager.GetString("Menu_File_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Action.
        /// </summary>
        public static string MessageBox_Confirm_DefaultTitle {
            get {
                return ResourceManager.GetString("MessageBox_Confirm_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string MessageBox_DefaultButton {
            get {
                return ResourceManager.GetString("MessageBox_DefaultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MessageBox_NoButton {
            get {
                return ResourceManager.GetString("MessageBox_NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MessageBox_YesButton {
            get {
                return ResourceManager.GetString("MessageBox_YesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string Operations_PanelTitle {
            get {
                return ResourceManager.GetString("Operations_PanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Progress_CancelButton {
            get {
                return ResourceManager.GetString("Progress_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Connection....
        /// </summary>
        public static string Progress_Testing {
            get {
                return ResourceManager.GetString("Progress_Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap server_add {
            get {
                object obj = ResourceManager.GetObject("server_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap server_delete {
            get {
                object obj = ResourceManager.GetObject("server_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Status_Loading {
            get {
                return ResourceManager.GetString("Status_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect....
        /// </summary>
        public static string ToolBar_Connect {
            get {
                return ResourceManager.GetString("ToolBar_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string TreeView_Disconnect {
            get {
                return ResourceManager.GetString("TreeView_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string TreeView_NoData {
            get {
                return ResourceManager.GetString("TreeView_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string TreeView_Refresh {
            get {
                return ResourceManager.GetString("TreeView_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hub has been updated to a new version..
        /// </summary>
        public static string Upgraded_Label {
            get {
                return ResourceManager.GetString("Upgraded_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Upgraded_OK {
            get {
                return ResourceManager.GetString("Upgraded_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hub Upgraded.
        /// </summary>
        public static string Upgraded_Title {
            get {
                return ResourceManager.GetString("Upgraded_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A host name or IP address is required.
        /// </summary>
        public static string Validator_Host_Error {
            get {
                return ResourceManager.GetString("Validator_Host_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port must be an integer value between 0 and 65535 inclusive.
        /// </summary>
        public static string Validator_Port_Error {
            get {
                return ResourceManager.GetString("Validator_Port_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- 0.3.0.2 ---
        ///
        ///- Mongo DB Plugin
        ///  - Changed system overview virtual memory chart to the more useful virtual memory
        ///
        ///--- 0.3.0.1 ---
        ///
        ///- Mongo DB Plugin
        ///  - Added a system overview page
        ///
        ///--- 0.3.0.0 ---
        ///
        ///- Can specify a friendly name for connections
        ///- Mongo DB Plugin
        ///  - Replaced Evaluate JavaScript window with a more useful mongo shell wrapper
        ///
        ///--- 0.2.0.11 ---
        ///
        ///- Mongo DB Plugin
        ///  - Obtaining replica set status now done with EvalFlags.NoLock
        ///  - Fixed errant Copy Collections window si [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Versions {
            get {
                return ResourceManager.GetString("Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wait {
            get {
                object obj = ResourceManager.GetObject("wait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
